export const GET_ROOM_PHOTOS = 'GET_ROOM_PHOTOS';
export const ADD_ROOM_PHOTOS = 'ADD_ROOM_PHOTOS';
export const UPDATE_ROOM_PHOTOS = 'UPDATE_ROOM_PHOTOS';
export const DELETE_ROOM_PHOTOS = 'DELETE_ROOM_PHOTOS';
